[env:esp32-8048s070]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
build_flags = -DBOARD_HAS_PSRAM -DLV_CONF_INCLUDE_SIMPLE -DLV_CONF_SUPPRESS_DEFINE_CHECK -DLV_USE_DEMO_WIDGETS=0 -I./src
lib_deps =
    lovyan03/LovyanGFX@^1.1.15
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^7.0.4