; PlatformIO Project Configuration File for ROBOBUILDERS RB2556 ESP32 (esp32_relay_30a_x1_v1.1)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM3
monitor_port = COM3

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

build_flags =
    -D CORE_DEBUG_LEVEL=2
