#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_MEM_SIZE (48U * 1024U)
#define LV_DPI_DEF 130
#define LV_DRAW_COMPLEX 1
#define LV_USE_LOG 1
#define LV_LOG_PRINTF 1

#define LV_USE_THEME_DEFAULT 1
#define LV_THEME_DEFAULT_DARK 1
#define LV_USE_FLEX 1
#define LV_USE_GRID 1

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_48 1

#define LV_USE_BTN 1
#define LV_USE_LABEL 1

#define LV_USE_ANIMATION 1
#define LV_USE_SHADOW 1

#endif